config/routes.rb
Rails.application.routes.draw do
  get "lectures/index"
  get "lectures/new"
  devise_for :users

  resources :users, only: [:show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

 resources :tweets
  root 'tweets#index'


resources :perfumes


   #root 'lectures#index'
  get 'lectures/index'  => 'lectures#index'
  get 'lectures/new'  => 'lectures#new'
  post 'lectures/new'  => 'lectures#create'



end

app/models/amusement.rb
class Amusement < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/lecture.rb
class Lecture < ApplicationRecord
end

app/models/perfume.rb
class Perfume < ApplicationRecord
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 has_many :tweets, dependent: :destroy 
  validates :name, presence: true 
  validates :profile, length: { maximum: 200 }


         has_many :tweets

 has_one_attached :image 

end

app/controllers/amusements_controller.rb
class AmusementsController < ApplicationController

 def index
        @amusements = Amusement.all
    end

     def new
    @amusement = Amusement.new
  end

  def create
    amusement = Amusement.new(tweet_params)
    if amusement.save!
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end

  private
  def amusement_params
    params.require(:amusement).permit(:att_name, :park_name, :comment)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

 before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    # サインアップ時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    # アカウント編集の時にnameとprofileのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
  end

end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  def index
   @lectures = Lecture.all
  end
  
  def new
    @lecture = Lecture.new
  end

  def create
    @lecture = Lecture.new(lecture_params)

    if @lecture.save 
      redirect_to action: 'index'
    else 
      redirect_to action: 'new'
    end
  end



  private

  def lecture_params
    params.require(:lecture).permit(:name,:username, :overall,:level)
  end
end

app/controllers/perfumes_controller.rb
class PerfumesController < ApplicationController
    def index
    end

    def new
        @perfume = Perfume.new
    end

    def show
        @perfume = Perfume.find_by(id: params[:id])
    end

    def create
        perfume = Perfume.new(perfume_params)
        if perfume.save
            flash[:notice] = "診断が完了しました"
            redirect_to perfume_path(perfume.id)
        else
            redirect_to :action => "new"
        end
    end
  
  private
    def perfume_params
        params.require(:perfume).permit(:question1, :question2, :question3, :question4)
    end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

    before_action :authenticate_user!, only: [:new, :create]

 def index
        @tweets = Tweet.all
    end

    def new
    @tweet = Tweet.new
  end

  def create
    tweet = Tweet.new(tweet_params)

tweet.user_id = current_user.id

    if tweet.save!
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end

  private
  def tweet_params
    params.require(:tweet).permit(:name, :access, :comments,:image)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

 def show
    @user = User.find(params[:id]) 
  end

end

app/helpers/amusements_helper.rb
module AmusementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper

 def getPercent(number) 
   if number.present?
     calPercent = number/5.to_f * 100
     # calPercent = number/10.to_f * 100
     #↑１０段階評価の際は2行目コメントアウトを外して、1行目をコメントアウト。
     percent = calPercent.round
     #↑CSSは小数が含まれると、widthの幅を指定できないので四捨五入して整数化。
     return percent.to_s
   else
     return 0
   end
 end

end

app/helpers/perfumes_helper.rb
module PerfumesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Amuse" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

<body>
 <header>
  <h1>Enjoy Amusement</h1>
  <div class="header-list">
   <ul>
    <% if user_signed_in? %>
     <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
    <% else %>
     <li><%= link_to "新規登録", new_user_registration_path %></li>
     <li><%= link_to "ログイン", new_user_session_path %></li>
    <% end %>
   </ul>
  </div>
 </header>
 <main>
  <%= yield %>
 </main>
</body>


</html>

app/views/lectures/index.html.erb
<%= link_to '新規アトラクション評価を登録をする', lectures_new_path,class: "theme-button" %>

<h1>アトラクション評価一覧</h1>

<% @lectures.each do |t|%>
<div style = 'margin:20px; border:2px double black; width:500px;padding-left:20px;'>
   <h2> 授業名：<%= t.name %> </h2>
   <h4>投稿者:<%= t.username%></h4>

<!--- 総合評価の星の部分 ---------->

<div>
<h2>総合評価：
<span class="star-rating">
   <span class="star-rating-front" style="width: <%= getPercent(t.overall) %>%;">★★★★★</span>
   <span class="star-rating-back">★★★★★</span>
</span> 
</h2>
</div>

<!--- 総合評価の星の部分終わり------->


<!--- 授業レベルの星の部分 ------------>
<div>
<h2>授業レベル：
<span class="star-rating">
   <span class="star-rating-front" style="width: <%= getPercent(t.level) %>%;">★★★★★</span>
   <span class="star-rating-back">★★★★★</span>
</span>
</h2>
</div>
<!--- 授業レベルの星の部分終わり-------->

</div>
<% end %>


<%= link_to '閉じる', {controller: "tweets", action: "index"}, class: "close-button" %>

app/views/lectures/new.html.erb
<%= form_with model: @lecture , url: lectures_new_path ,local: true do |f| %>
  <div class="lecture_form">
  <h3>投稿フォーム</h3>
  <%= f.text_field :name , placeholder: 'アトラクション名を入力', class:'name_field'%>
  <%= f.text_field :username , placeholder: '投稿者名を入力', class:'name_field'%>

  <h5>総合評価</h5>
   <div class="post_form">
    <%= f.radio_button :overall, 5 ,id: 'star1'%>
    <label for="star1"><span class="text">最高</span>★</label>

    <%= f.radio_button :overall, 4 ,id: 'star2'%>
    <label for="star2"><span class="text">良い</span>★</label>

    <%= f.radio_button :overall, 3 ,id: 'star3'%>
    <label for="star3"><span class="text">普通</span>★</label>

    <%= f.radio_button :overall, 2 ,id: 'star4'%>
    <label for="star4"><span class="text">悪い</span>★</label>

    <%= f.radio_button :overall, 1 ,id: 'star5'%>
    <label for="star5"><span class="text">最悪</span>★</label>
 </div>

<h5>絶叫レベル</h5>
  <div class="post_form">
    <%= f.radio_button :level,  5 ,id: 'star6'%>
    <label for="star6"><span class="text">最恐</span>★</label>

    <%= f.radio_button :level,  4 ,id: 'star7'%>
    <label for="star7"><span class="text">恐い</span>★</label>

    <%= f.radio_button :level, 3 ,id: 'star8'%>
    <label for="star8"><span class="text">爽快</span>★</label>

    <%= f.radio_button :level , 2 ,id: 'star9'%>
    <label for="star9"><span class="text">恐くない</span>★</label>

    <%= f.radio_button :level , 1 ,id: 'star10'%>
    <label for="star10"><span class="text">物足りない</span>★</label>
 </div>


  </div>
  <%= f.submit '送信'%>
  

<% end %>

<%= link_to '閉じる', {controller: "tweets", action: "index"}, class: "close-button" %>

app/views/perfumes/index.html.erb
<h1>香水診断スタート</h1>
<%= link_to "診断を始める", new_perfume_path, class: "link" %>

app/views/perfumes/new.html.erb
<%= form_for(@perfume, class: 'form-horizontal', role: 'form') do |f| %>
    <div class="perfume-container">
        <div class="col-12">
            <p>Q1. 速い乗り物は…</p>
        </div>
        <div class="col-6">
            <%= f.radio_button :question1, "1", id: "custom_id1" %>
            <label for="custom_id1">得意だ</label>
            <%= f.radio_button :question1, "2", id: "custom_id2" %>
            <label for="custom_id2">苦手だ</label>
        </div>
        <div class="col-12">
            <p>Q2. 高い場所は…</p>
        </div> 
        <div class="col-6">
            <%= f.radio_button :question2, "1", id: "custom_id3" %>
            <label for="custom_id3">得意だ</label>
            <%= f.radio_button :question2, "2", id: "custom_id4" %>
            <label for="custom_id4">苦手だ</label>
        </div>   
        <div class="col-12">
            <p>Q3. 三半規管は…</p>
        </div>
        <div class="col-6">
            <%= f.radio_button :question3, "1", id: "custom_id5" %>
            <label for="custom_id5">強いほうだ</label>
            <%= f.radio_button :question3, "2", id: "custom_id6" %>
            <label for="custom_id6">弱いほうだ</label>
        </div>
    
        <div class="col-12">
            <p>Q4. 浮遊感は…</p>
        </div>
        <div class="col-6">
            <%= f.radio_button :question4, "1", id: "custom_id7" %>
            <label for="custom_id7">得意だ</label>
            <%= f.radio_button :question4, "2", id: "custom_id8" %>
            <label for="custom_id8">苦手だ</label>
        </div>
    </div>
    <div class="sindanbotan">
        <%= f.submit " 結果 " %>
<div class="coaster-supports"></div>

    </div>


        <%= link_to '閉じる', {controller: "tweets", action: "index"}, class: "close-button" %>

         
  <footer>	
  </footer>
<% end %>

app/views/perfumes/show.html.erb
<div class="intoro">
  <h1>診断結果</h1>
  <h2>あなたの絶叫耐性レベルは...</h2>
</div>
<div class="perfume-container">
  <% case [@perfume.question1, @perfume.question2, @perfume.question3, @perfume.question4] %>
  <% when ["1", "1", "1", "1"] %>
    <h6>スチール・ドラゴン2000（ナガシマスパーランド）　レベル</h6>
    <p>世界最長のコースター！高さ、速さも日本一！</p>
    <p>もはや恐いものなし！</p>
  <% when ["1", "1", "1", "2"] %>
    <h6>ザ・フライング・ダイナソー（ユニバーサル・スタジオ・ジャパン）　レベル</h6>
    <p>プテラノドンに掴まれながら、空を飛び回ろう！</p>
    <p>うつ伏せになっていることで、浮遊感が感じにくいらしい？</p>
  <% when ["1", "1", "2", "1"] %>
    <h6>サンダードルフィン（東京ドームシティ）　レベル</h6>
    <p>東京の街を爽快に駆け抜けるアトラクション！</p>
    <p>回転がなく、三半規管が弱い人にもおすすめ！</p>
  <% when ["1", "1", "2", "2"] %>
    <h6>センター・オブ・ジ・アース（東京ディズニーシー）　レベル</h6>
    <p>急激なスピードアップ＆急上昇！</p>
    <p>浮遊感は一瞬だけ！</p>
  <% when ["1", "2", "1", "1"] %>
    <h6>白鯨（ナガシマスパーランド）　レベル</h6>
    <p>国内屈指の絶叫系アトラクション！</p>
    <p>コースが真っ白で美しい！</p>
  <% when ["1", "2", "1", "2"] %>
    <h6>レイジング・スピリッツ（東京ディズニーシー）　レベル</h6>
    <p>ぐるっと１回転すること特徴のコースター</p>
    <p>高さはあまりなく、絶叫系が苦手な人も挑戦しやすい！</p>
  <% when ["1", "2", "2", "1"] %>
    <h6>スペース・マウンテン（東京ディズニーランド）　レベル</h6>
    <p>暗闇の中を駆け抜ける！</p>
    <p>周りが見えないからこそ恐くないかも！？</p>
  <% when ["1", "2", "2", "2"] %>
    <h6>ZOKKON（富士急ハイランド）　レベル　</h6>
    <p>バイク型のライドに乗って駆け抜けるアトラクション</p>
    <p>回転や落差が少なく、スピード感による爽快感が存分に味わえる！</p>
  <% when ["2", "1", "1", "1"] %>
    <h6>岐阜バンジー（岐阜県）　レベル</h6>
    <p>国内最大級のバンジージャンプ</p>
    <p>人によってはどんなアトラクションよりも恐いかも！？</p>
  <% when ["2", "1", "1", "2"] %>
    <h6>ビッグサンダー・マウンテン（東京ディズニーランド）　レベル</h6>
    <p>ディズニーランドの代表的アトラクション</p>
    <p>スピード・浮遊感ともに小さく、絶叫系が苦手な人も挑戦しやすい！</p>
  <% when ["2", "1", "2", "1"] %>
    <h6>スプラッシュ・マウンテン（東京ディズニーランド）　レベル</h6>
    <p>ディズニーランドの代表的アトラクション</p>
    <p>高いところからの景色を楽しんじゃおう！</p>
  <% when ["2", "1", "2", "2"] %>
    <h6>観覧車　レベル</h6>
    <p>高いところが大丈夫なあなたは</p>
    <p>観覧車からの素敵な景色とともに、ゆったりとした時間の流れを楽しもう！</p>
  <% when ["2", "2", "1", "1"] %>
    <h6>タワー・オブ・テラー（東京ディズニーシー）　レベル</h6>
    <p>浮遊感MAXのアトラクション</p>
    <p>高さはあるけれど、きれいな景色を目に焼き付けよう！</p>
  <% when ["2", "2", "1", "2"] %>
    <h6>コーヒーカップ　レベル</h6>
    <p>回転に強いあなたは</p>
    <p>コーヒーカップで主導権を握って、ハンドルをガンガン回しちゃおう！</p>
  <% when ["2", "2", "2", "1"] %>
    <h6>ローラーコースター（浅草花やしき）　レベル</h6>
    <p>日本最古のコースター！</p>
    <p>スピード控えめで挑戦しやすい！</p>
  <% when ["2", "2", "2", "2"] %>
    <h2>キャラクターとミート＆グリート　レベル</h2>
    <p>遊園地＝アトラクションだけではない！</p>
    <p>キャラクターとの平和な時間を過ごそう！</p>
  <% end %>

  
<%= link_to '閉じる', :controller => "tweets", :action => "index" %>

</div>

app/views/tweets/index.html.erb
  <% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id), class: "link" %>
  

<h1>絶叫レベル診断</h1>
<%= link_to "診断を始める", new_perfume_path, class: "link" %>

<h1>アトラクション評価</h1>
<%= link_to '評価を始める',lectures_index_path, class: "link" %>

 <div class="coaster-supports"></div>

  
  <h1>アトラクション口コミ</h1>

<%= link_to "新規投稿へ", new_tweet_path, class: "link" %>
<% end %>

<div class="tweets-container">
  <% @tweets.each do |t| %>
    <div class="tweet">

      <%= t.user.email %>

  
      
        <%= t.name %>
        <%= t.access %>
        <%= t.comments %>
      <% if t.image.attached? %> 
      <%= image_tag t.image, size: "250x200" %> 
      <% else %>
      <%= image_tag "default.png", size: "250x200" %> 
      <% end %>

    </div>
    



    
  <% end %>
</div>


 

app/views/tweets/new.html.erb
<h1>(アトラクション口コミ)</h1>
<h3>新規投稿ページ</h3>
<%= form_for @tweet do |f| %>


  <div class="field">
    <%= f.label :名前 %>
    <%= f.text_field :name, :size => 30 %>
  </div>


  <div class="field">
    <%= f.label :アクセス %>
    <%= f.text_field :access, :access => 30 %>
  </div>


  <div class="field">
    <%= f.label :コメント %>
    <%= f.text_field :comments, :size => 30 %>
  </div>




 <div class="field">
    <%= f.label :画像%>
    <%= f.file_field :image %>
  </div>

  <%= f.submit "投稿する" %>
<% end %>

<%= link_to "一覧に戻る", tweets_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>マイページ</h1>
<div class="user-info-strong">
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>

</div>



<div class="user-page">
<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.tweets.each do |t| %>
    
  <%= t.user.name %>
   
<% end %>



<%= link_to "Tweet一覧に戻る", tweets_path %>
  </div>